version: '3.8'

services:
  storage:
    image: cassandra:3.11
    # Uncomment to use DSE instead (minimum version 5.1)
    # image: datastax/dse-server:5.1.20
    # environment:
    #  - DS_LICENSE=accept
    environment:
      MAX_HEAP_SIZE: 1G
      HEAP_NEWSIZE: 256M
      CASSANDRA_CLUSTER_NAME: zipkin
      CASSANDRA_DC: dc1
      CASSANDRA_RACK: rack1
    container_name: cassandra
    ports:
      - 9042:9042
    healthcheck:
      test: ["CMD-SHELL", "cqlsh localhost 9042 -e 'describe keyspaces'"]
      interval: 30s
      timeout: 10s
      retries: 10
      start_period: 40s

  # Use Cassandra instead of in-memory storage
  zipkin:
    extends:
      file: docker-compose.yml
      service: zipkin
    # slim doesn't include Cassandra support, so switch to the larger image
    image: ghcr.io/openzipkin/zipkin:${TAG:-latest}
    environment:
      - STORAGE_TYPE=cassandra3
      # When using the test docker image, or have schema pre-installed, you don't need to ensure it
      - CASSANDRA_ENSURE_SCHEMA=false
      # When overriding this value, note the minimum supported version is 3.11.3
      - CASSANDRA_CONTACT_POINTS=cassandra
      # Uncomment to configure authentication
      # - CASSANDRA_USERNAME=cassandra
      # - CASSANDRA_PASSWORD=cassandra
    # Uncomment to enable request logging (TRACE shows query values)
    # command: --logging.level.com.datastax.oss.driver.internal.core.tracker.RequestLogger=TRACE
    depends_on:
      storage:
        condition: service_healthy

  dependencies:
    extends:
      file: docker-compose-dependencies.yml
      service: dependencies
    environment:
      - STORAGE_TYPE=${STORAGE_TYPE:-cassandra3}
      - CASSANDRA_CONTACT_POINTS=cassandra
    depends_on:
      storage:
        condition: service_healthy
